name: Deploy Lambda

on:
  workflow_dispatch:
  push:
    tags:
      - v*

jobs:
  deploy-prod:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2
    - name: Node.js Setup
      uses: actions/setup-node@v1
    - name: Install Serverless Framework
      run: npm install -g serverless@2.54.0
    - name: Serverless AWS authentication
      run: serverless config credentials --provider AWS --key ${{ secrets.AWS_ACCESS_KEY_ID }} --secret ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    - name: Deploy Lambda functions
      run: make deploy
